### ISSUE TITLE
Build UML vocab and concept DB

### ISSUE THREAD

**Issue by analyticalpicasso** [CogStack/MedCATtutorials#2]
Hello,

Is there any tutorial on how to build concept DB and vocab using complete UML? I also would like to know if we can add all UML synonyms to fetch Snomed concepts.

**Comment by antsh3k** [comment]
Unfortunately there is not at this current point in time.
You can build your own UMLS concept DB after processing into the same format outlined in [Tutorial Part 3.1](https://github.com/CogStack/MedCATtutorials/blob/main/notebooks/introductory/Part_3_1_Building_a_Concept_Database_and_Vocabulary.ipynb).

Alternatively you can explore one of the preexisting models which can be found [here.](https://medcat.readthedocs.io/en/latest/main.html#models)
