### ISSUE TITLE
Links to source files for tutorials have been moved

### ISSUE THREAD

**Issue by antsh3k** [CogStack/MedCATtutorials#8]
The source files for raw data and medcat models have broken links due to server migration. New destination needs to be created for these files and links changed throughout tutorials

**Comment by baixiac** [comment]
Any idea if this issue is still relevant? If yes, should the CI capture that and be failing already?

**Comment by antsh3k** [comment]
So any files in the tutorials that require files from https://medcat.rosalind.kcl.ac.uk will be removed. The links still work but since Rosalind will be decommissioned in the coming months, the files removed. We need to find another home for these files

**Comment by baixiac** [comment]
Tacked by [CU-862jgz51z](https://app.clickup.com/t/862jgz51z).

**Comment by baixiac** [comment]
Closed by https://github.com/CogStack/MedCATtutorials/pull/12.
